version: "3.8"
services:
  handali-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: handali-prod
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    restart: unless-stopped
