INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '원룸', 10000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '빌라', 15000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '아파트', 20000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '스위트룸', 30000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '고풍스러운 서재', 25000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '미니멀리스트 거실', 18000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '화려한 펜트하우스', 40000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '일본식 다다미방', 12000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '유럽풍 클래식 인테리어', 35000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('배경', '따뜻한 카페 스타일 공간', 22000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '나무 의자', 5000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '철제 의자', 7000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '디자인 의자', 12000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '나무 소파', 15000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '푹신한 소파', 20000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '철제 소파', 18000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '디자인 소파', 25000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '가죽 소파', 30000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '모듈형 소파', 35000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('소파', '빈티지 패브릭 소파', 28000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '나무 시계', 8000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '철 창문', 12000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '값싼 액자', 5000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '비싼 액자', 20000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '모던한 벽걸이 선반', 15000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '빈티지 거울', 18000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', 'LED 네온 사인', 25000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '그림 액자', 10000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '벽걸이 플랜트', 22000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('벽장식', '세계 지도 장식', 30000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '스탠딩 조명', 12000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '크리스마스 트리', 15000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '모던 러그', 18000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '대형 화분', 20000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '빈티지 서랍장', 25000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '자동 로봇 청소기', 40000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '책 무더기', 5000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '불멍용 미니 화로', 28000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '전신 거울', 22000, false);
INSERT INTO store_items (category, name, price, is_buy) VALUES ('바닥장식', '앤틱 보석함', 35000, false);